//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_stock
    {
        public int ID { get; set; }
        public string Product_name { get; set; }
        public string Unit_measurement { get; set; }
        public int Price { get; set; }
        public int Quantity_product { get; set; }
        public int INN { get; set; }
    }
}
