//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public System.DateTime Date_sale { get; set; }
        public string List_products { get; set; }
        public string Quantity { get; set; }
        public int Amount_sale { get; set; }
    }
}
