//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int ID { get; set; }
        public System.DateTime Delivery_date { get; set; }
        public int ID_supplier { get; set; }
        public string List_products { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
